@startuml 2022 URI Laser Scarecrow State Model
'plantUML https://plantuml.com/
'in Visual Studio, look for the PlantUML extension by jebbs

state read_tape_setting <<choice>>
read_tape_setting : Jumper Mode
read_tape_setting --> Active : [ignore tape]
read_tape_setting --> SelfTest : [self-test]
read_tape_setting --> MapSeekHome : [else]

[*] --> PowerOn

state PowerOn
PowerOn : /entry: initialize GPIO; read tape mode jumper
PowerOn --> read_tape_setting

state SelfTest {
  [*] --> HoldServo
  HoldServo : /entry: set servo to midpoint; set 5 second timer; beep welcome (?)
  HoldServo --> SelfTestActive : [timer elapsed]
  SelfTestActive --> SelfTestTilt : LSEVT_TILTED_PAST_THRESHOLD
  SelfTestActive : /do:\n* pulse laser;\n* move forward 2 reverse 1\n* servo sweep\n* click on magnet\n* beep on tape transition
  SelfTestTilt --> SelfTestActive : LSEVT_TILTED_OKAY
  SelfTestTilt : /entry: stop movement
  SelfTestTilt : /do: tilt error code beep frequently
  note as NoteSelfTest
  SelfTest can be exited
  only by powering down
  and setting tape mode jumper
  end note
}

state PreLaserWarningActive
PreLaserWarningActive : /do: rotate full speed; make annoying sounds
PreLaserWarningActive --> Active : LSEVT_BUZZER_WARNING_COMPLETE

state Active {
  [*] -->  Running
  Running : /do: random movement; laser per map
  Running --> ActiveSeekHome : LSEVT_HOME_EXPIRED
  ActiveSeekHome --> Running : LSEVT_HOME_COMPLETED
  ActiveSeekHome --> HomeError : LSEVT_HOME_FAILED
  ActiveSeekHome : /do: forward other events to SeekHome
}

Active --> Sleep : LSEVT_LIGHT_NIGHT
Active --> SettingsUpperSwitch : LSEVT_CONTROLS_UPPER
Active --> SettingsLowerSwitch : LSEVT_CONTROLS_LOWER
Active --> SettingsBothSwitches : LSEVT_CONTROLS_BOTH

state Home {
  [*] --> RotateToMagnet
  RotateToMagnet --> SeekHomeFailed : LSEVT_STEPPER_FINISHED_MOVE [foundMagnet==false]
  RotateToMagnet --> BackUpPastMagnet : LSEVT_STEPPER_FINISHED_MOVE [foundMagnet==true]
  RotateToMagnet : /entry stepper forward 3 revolutions
  RotateToMagnet : /foundMagnet=true : LSEVT_MAGNET_ENTER
  RotateToMagnet : /stepper_stop : LSEVT_MAGNET_ENTER

  BackUpPastMagnet --> SlowSeekToMagnet : LSEVT_STEPPER_FINISHED_MOVE
  BackUpPastMagnet : /entry stepper_reverse
  BackUpPastMagnet --> BackUpPastMagnet : LSEVT_STEPPER_FINISHED_MOVE\n[tries > 0]
  BackUpPastMagnet --> SeekHomeFailed : LSEVT_STEPPER_FINISHED_MOVE\n[tries <= 0]
  SlowSeekToMagnet : /entry: tries := 50
  SlowSeekToMagnet : /do: stepper forward 1; tries--
  SlowSeekToMagnet --> SlowSeekToMagnet : LSEVT_STEPPER_FINISHED_MOVE\[tries > 0]
  SlowSeekToMagnet --> SeekHomeFailed : LSEVT_STEPPER_FINISHED_MOVE\n[tries <= 0]
  SlowSeekToMagnet --> SeekHomeComplete : LSEVT_MAGNET_ENTER
  SeekHomeComplete : /entry: queue LSEVT_HOME_COMPLETED
  SeekHomeComplete --> [*]
  SeekHomeFailed : /entry: queue LSEVT_HOME_FAILED
  SeekHomeFailed --> HomeError
}
Home : /entry: laser OFF; set tries=0
Home : /exit: record home location (stepper_step := 0)

state HomeError
HomeError : /entry: turn off devices
HomeError : /do: home error code beeps periodically; status LEDs pulse red
HomeError --> HomeError


state MapBuild {
  [*] --> SeekHome
  SeekHome --> BuildMap : [HomedSuccessfully]
  BuildMap : /entry: read tape mode; set map_optional and thresholds; enable reflectance sensor
  BuildMap : /do: step stepper and read tape reflectance levels for one rotation
  BuildMap : /exit: disable reflectance sensor; check map - map_built := tape sections detected AND bucket sections detected
  BuildMap --> BuildMapError : [!map_built && !map_optional]
  BuildMap --> PreLaserWarningActive : [map_built || map_optional)]
  BuildMapError : /entry: turn off devices
  BuildMapError : /do: tape error code beeps periodically
}

MapSeekHome --> MapBuild : LSEVT_HOME_COMPLETED
MapSeekHome --> HomeError : LSEVT_HOME_FAILED
MapSeekHome : /do: forward other events to SeekHome


state Sleep
Sleep : /entry: turn off all devices
Sleep : /do: check ambient light; snore
Sleep : /exit: do pre-laser wawrning
Sleep --> PreLaserWarningActive : LSEVT_LIGHT_DAY
Sleep --> SettingsUpperSwitch : LSEVT_CONTROLS_UPPER
Sleep --> SettingsLowerSwitch : LSEVT_CONTROLS_LOWER
Sleep --> SettingsBothSwitches : LSEVT_CONTROLS_BOTH

SettingsUpperSwitch : /entry: play settings tune once
SettingsUpperSwitch : /do: status LEDs flash yellow
SettingsUpperSwitch : /do: rotate forward 450 degrees at a time
SettingsUpperSwitch : /do: sweep angle from top to bottom
SettingsUpperSwitch : /LSEVT_CONTROLS_SLIDER1: set rotation speed
SettingsUpperSwitch : /LSEVT_CONTROLS_SLIDER2: set angle speed
SettingsUpperSwitch : /LSEVT_CONTROLS_OFF: save settings
SettingsUpperSwitch --> SettingsLowerSwitch : LSEVT_CONTROLS_LOWER
SettingsUpperSwitch --> SettingsBothSwitches : LSEVT_CONTROLS_BOTH
SettingsUpperSwitch --> Active : LSEVT_CONTROLS_OFF

SettingsLowerSwitch : /entry: play settings tune twice
SettingsLowerSwitch : /do: status LEDs flash magenta 2x
SettingsLowerSwitch : /do: rotate forward 450 degrees at a time
SettingsLowerSwitch : /do: sweep angle from top to bottom
SettingsLowerSwitch : /LSEVT_CONTROLS_SLIDER1 : set top angle
SettingsLowerSwitch : /LSEVT_CONTROLS_SLIDER2 : set bottom angle
SettingsLowerSwitch : /LSEVT_CONTROLS_OFF: save settings
SettingsLowerSwitch --> SettingsUpperSwitch : LSEVT_CONTROLS_UPPER
SettingsLowerSwitch --> SettingsBothSwitches : LSEVT_CONTROLS_BOTH
SettingsLowerSwitch --> Active : LSEVT_CONTROLS_OFF

SettingsBothSwitches : /entry: play settings tune 3x
SettingsBothSwitches : /entry: stop movement; turn off laser
SettingsBothSwitches : /do: status LEDs flash magenta and yellow
SettingsBothSwitches : /LSEVT_CONTROLS_SLIDER1 : set light sensitivity
SettingsBothSwitches : /LSEVT_CONTROLS_OFF: save settings
SettingsBothSwitches --> SettingsUpperSwitch : LSEVT_CONTROLS_UPPER
SettingsBothSwitches --> SettingsLowerSwitch : LSEVT_CONTROLS_LOWER
SettingsBothSwitches --> Active : LSEVT_CONTROLS_OFF

@enduml
